name: Publish Package to npmjs

on:
  release:
    types:
      - [created]
      
jobs:
  build:
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: [14.x, 16.x, 18.x, 20.x]

    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node_version}}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}
          registry-url: 'https://registry.npmjs.org'

      - name: npm ci
        run: npm ci

      - name: npm publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}