name: Test Coverage

on:
  pull_request:
    branches: [main]

jobs:
  tests: 
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: [14.x, 16.x, 18.x, 20.x]

    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node_version}}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node_version}}

      - name: npm ci
        run: npm ci

      - name: test coverage
        run: npm test -- --coverage